#spring:
#  mail:
#    protocol: smtp
#    host: smtp.gmail.com
#    port: 587
#    username: ziaulfarha@gmail.com
#    password: 51885438
#    properties:
#      mail:
#       smtp:
#        auth: true
#        starttls:
#         enable: true
